services:
  electron-builder:
    build: .
    platform: linux/amd64
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
    environment:
      - NODE_ENV=production
    command: >
      sh -c "echo '=== Installing dependencies ===' &&
             export NODE_ENV=development &&
             npm install &&
             export NODE_ENV=production &&
             echo '=== Checking if Babel plugin is installed ===' &&
             npm list @babel/plugin-transform-private-property-in-object &&
             echo '=== Starting build ===' &&
             npm run electron-build -- --win"

volumes:
  node_modules:
  dist:
